package CapaPresentacion.GUI_Cliente;

/**
 *
 * @author ASUS
 */
public class CarritoCompras extends javax.swing.JPanel {


    public CarritoCompras() {
        initComponents();
    }

    
    /*

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class CarritoCompras extends JPanel {

    private JTable tablaProductos;
    private DefaultTableModel modeloTabla;

    private JLabel lblTotal;
    private JButton btnAceptarCompra;

    private double total = 0;

    public CarritoCompras() {
        inicializarComponentes();
    }

    private void inicializarComponentes() {

        setLayout(new BorderLayout());
        setBackground(new Color(26, 30, 41));
        setPreferredSize(new Dimension(1600, 1000));

        JLabel titulo = new JLabel("CARRITO DE COMPRAS");
        titulo.setHorizontalAlignment(SwingConstants.CENTER);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("Segoe UI", Font.BOLD, 30));
        titulo.setBorder(BorderFactory.createEmptyBorder(20, 0, 20, 0));

        add(titulo, BorderLayout.NORTH);

        modeloTabla = new DefaultTableModel(
                new Object[]{"Producto", "Precio"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaProductos = new JTable(modeloTabla);
        tablaProductos.setRowHeight(30);

        JScrollPane scroll = new JScrollPane(tablaProductos);

        add(scroll, BorderLayout.CENTER);

        JPanel panelInferior = new JPanel(new BorderLayout());
        panelInferior.setBackground(new Color(26, 30, 41));
        panelInferior.setBorder(BorderFactory.createEmptyBorder(15, 20, 15, 20));

        lblTotal = new JLabel("Total: $0");
        lblTotal.setForeground(Color.WHITE);
        lblTotal.setFont(new Font("Segoe UI", Font.BOLD, 22));

        btnAceptarCompra = new JButton("Aceptar Compra");
        btnAceptarCompra.setFont(new Font("Segoe UI", Font.BOLD, 18));
        btnAceptarCompra.setBackground(new Color(1, 128, 95));
        btnAceptarCompra.setForeground(Color.WHITE);
        btnAceptarCompra.setFocusPainted(false);

        btnAceptarCompra.addActionListener(e -> confirmarCompra());

        panelInferior.add(lblTotal, BorderLayout.WEST);
        panelInferior.add(btnAceptarCompra, BorderLayout.EAST);

        add(panelInferior, BorderLayout.SOUTH);
    }

    public void agregarProducto(String nombre, double precio) {

        modeloTabla.addRow(new Object[]{
            nombre,
            "$" + String.format("%,.0f", precio)
        });

        total += precio;

        actualizarTotal();
    }

    private void actualizarTotal() {

        lblTotal.setText(
                "Total: $" + String.format("%,.0f", total)
        );
    }

    private void confirmarCompra() {

        if (modeloTabla.getRowCount() == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "No hay productos en el carrito.",
                    "Carrito vacío",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        StringBuilder resumen = new StringBuilder();

        resumen.append("RESUMEN DE COMPRA\n\n");

        for (int i = 0; i < modeloTabla.getRowCount(); i++) {

            resumen.append("- ")
                   .append(modeloTabla.getValueAt(i, 0))
                   .append(" | ")
                   .append(modeloTabla.getValueAt(i, 1))
                   .append("\n");
        }

        resumen.append("\n");
        resumen.append("TOTAL A PAGAR: $")
               .append(String.format("%,.0f", total));

        JOptionPane.showMessageDialog(
                this,
                resumen.toString(),
                "Compra Confirmada",
                JOptionPane.INFORMATION_MESSAGE
        );

        limpiarCarrito();
    }

    private void limpiarCarrito() {

        modeloTabla.setRowCount(0);

        total = 0;

        actualizarTotal();
    }
}
    */
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(1600, 1000));
        setPreferredSize(new java.awt.Dimension(1600, 1000));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
