package CapaPresentacion.GUI_Admin;

import CapaLogicaNegocio.Helpers.OSHelper;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Marlon Vargas
 */
public class Inicio extends javax.swing.JPanel {

    public Inicio() {
        initComponents();
        establecerFondo();
        establecerLogo();
    }
    
    /**
     * Carga la imagen de imgFondoInicio desde la carpeta Images y la asigna al JLabel fondo.
     */
    public void establecerFondo() {
        Image img = OSHelper.cargarImagenPng("imgFondoInicio");
        if (img != null) jlb_fondo.setIcon(new ImageIcon(img));
    }

    public void establecerLogo() {
        Image img = OSHelper.cargarImagenPng("Logo_Inicio");
        if (img != null) jlb_Logo.setIcon(new ImageIcon(img));
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Logo = new javax.swing.JLabel();
        jlb_fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jlb_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 810, 490));
        add(jlb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 880));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_Logo;
    private javax.swing.JLabel jlb_fondo;
    // End of variables declaration//GEN-END:variables
}
