package CapaPresentacion.GUI_Admin;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Marlon Vargas
 */
public class Inicio extends javax.swing.JPanel {

    public String s;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        s = Paths.get("").toAbsolutePath().toString();
        establecerFondo();
        establecerLogo();
    }
    
    /**
     * Carga la imagen de imgFondoInicio desde el sistema de archivos y la asigna al JLabel fondo.
     */
    public void establecerFondo() {
        Image img = null;
        try {
            String pathC = s + "\\Images\\" + "imgFondoInicio" + ".png";
            img = ImageIO.read(new File(pathC));
            jlb_fondo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println(ioexception);
        }
    }
    /**
     * Carga la imagen de Logo_Inicio desde el sistema de archivos y la asigna al JLabel Logo.
     */
    public void establecerLogo() {
        Image img = null;
        try {
            String pathC = s + "\\Images\\" + "Logo_Inicio" + ".png";
            img = ImageIO.read(new File(pathC));
            jlb_Logo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println(ioexception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Logo = new javax.swing.JLabel();
        jlb_fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jlb_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 810, 490));
        add(jlb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 880));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_Logo;
    private javax.swing.JLabel jlb_fondo;
    // End of variables declaration//GEN-END:variables
}
