package CapaPresentacion.GUI_Admin;

import CapaLogicaNegocio.Helpers.OSHelper;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Marlon Vargas
 */
public class Inicio extends javax.swing.JPanel {

    public Inicio() {
        initComponents();
        establecerFondo();
        establecerLogo();
    }
    
    /**
     * Carga la imagen de imgFondoInicio desde la carpeta Images y la asigna al JLabel fondo.
     */
    public void establecerFondo() {
        try {
            String ruta = OSHelper.getImageFilePath("imgFondoInicio");
            Image img = ImageIO.read(new File(ruta));
            jlb_fondo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println("Error cargando fondo: " + ioexception.getMessage());
        }
    }

    /**
     * Carga la imagen de Logo_Inicio desde la carpeta Images y la asigna al JLabel Logo.
     */
    public void establecerLogo() {
        try {
            String ruta = OSHelper.getImageFilePath("Logo_Inicio");
            Image img = ImageIO.read(new File(ruta));
            jlb_Logo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println("Error cargando logo: " + ioexception.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_Logo = new javax.swing.JLabel();
        jlb_fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jlb_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 810, 490));
        add(jlb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 880));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_Logo;
    private javax.swing.JLabel jlb_fondo;
    // End of variables declaration//GEN-END:variables
}
