/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion.GUI_Local;

import CapaPresentacion.GUI_Admin.InicioSesionAdministrador;
import CapaLogicaNegocio.Helpers.HelperMonitorRed;
import CapaLogicaNegocio.Helpers.HelperRed;
import CapaLogicaNegocio.Helpers.OSHelper;
import CapaDatos.Logica_Conexion.Conexion;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago Lopez
 */
public class Portada extends javax.swing.JFrame {

    /**
     * Creates new form Portada
     */
    public String pathc;
    public String s;
    
    public Portada() {
        initComponents();
        centerFrame();
        HelperMonitorRed monitor = new HelperMonitorRed();
        monitor.setDaemon(true);
        monitor.start();
        Conexion.Conectar();
        Path currentRelativePath = Paths.get("");
        s = currentRelativePath.toAbsolutePath().toString();
        establecerFondo();
        establecerIconoLogo();
        OSHelper.setImage(fondo, "usuario.png");
        OSHelper.setImage(icono_logo, "LogoF.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /**
     * Centra el JFrame en la pantalla al momento de mostrarse.
     */
    private void centerFrame() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screen.width - getWidth()) / 2, (screen.height - getHeight()) / 2);
    }
    
     /**
     * Carga el fondo desde el sistema de archivos y la asigna al JLabel fondo.
     */
    
    public void establecerFondo() {
        Image img = null;
        try {
            String pathIcono = s + "\\Images\\" + "BackgroundN2" + ".png";
            img = ImageIO.read(new File(pathIcono));
            fondo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println(ioexception);
        }
    }
    
    /**
     * Carga la imagen del logo desde el sistema de archivos y la asigna al JLabel icono_logo.
     */
    public void establecerIconoLogo() {
        Image img = null;
        try {
            String pathIcono = s + "\\Images\\" + "LogoImage" + ".png";
            img = ImageIO.read(new File(pathIcono));
            icono_logo.setIcon(new ImageIcon(img));
        } catch (IOException ioexception) {
            System.err.println(ioexception);
        }
    }
      
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        icono_logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 40)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Bienvenido");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Avanzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 30));
        getContentPane().add(icono_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 180));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 402));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		
		// 1. Mostramos un mensaje de que estamos verificando (opcional)
		System.out.println("Verificando estado de la red...");

		// 2. Usamos nuestro helper para decidir
		boolean usarNube = HelperRed.verificarConexion();

		if (usarNube) {
			// Hay internet rápido -> Vamos a la Nube
			JOptionPane.showMessageDialog(this, "Conexión óptima. Iniciando servicios en la Nube.");
			InicioSesionAdministrador admin = new InicioSesionAdministrador();
			admin.setVisible(true);
		} else {
			// No hay internet o es muy lento -> Vamos al modo Local
			JOptionPane.showMessageDialog(this, "Conexión inestable o sin red. Iniciando modo Local.");
			MenuLocal local = new MenuLocal();
			local.setVisible(true);
		}

		dispose();
		
		EscogerBD esco= new EscogerBD();
//      esco.setVisible(true);
//      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono_logo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
